### ISSUE TITLE
FreeSwitch 1.10.7 Crashs every day  

### ISSUE THREAD

**Issue by dxhgq-github** [freeswitch/sofia-sip#125]
Hello,

FreeSwitch crashs one or two times every 24 hours , the FS version is 1.10.7 ,the OS is centos 7  ,the only error messages in /var/log/messages is : 
Apr 25 12:19:43 localhost systemd: freeswitch.service: main process exited, code=killed, status=8/FPE
Apr 25 12:19:43 localhost systemd: Unit freeswitch.service entered failed state.
Apr 25 12:19:43 localhost systemd: freeswitch.service failed.

Backtrace:

(gdb) where
#0  0x00007f36d8db1c3d in su_block_add (b=0x7f36945a3ce0, p=0x7f3694a73170) at su_alloc.c:339
#1  0x00007f36d8db21f2 in sub_alloc (home=0x7f36944eea20, sub=0x7f36945a3ce0, size=80, 
    zero=do_calloc) at su_alloc.c:527
#2  0x00007f36d8db3d2f in su_zalloc (home=0x7f36944eea20, size=80) at su_alloc.c:1574
#3  0x00007f36d8d3dcf9 in outgoing_make_a_aaaa_query (orq=0x7f36945a4a40) at nta.c:10343
#4  0x00007f36d8d3d32e in outgoing_resolve_next (orq=0x7f36945a4a40) at nta.c:10124
#5  0x00007f36d8d3eda7 in outgoing_answer_srv (orq=0x7f36945a4a40, q=0x7f36945a4c20, 
    answers=0x7f369411dfa0) at nta.c:10707
#6  0x00007f36d8da5fd9 in sres_query_report_error (q=0x7f36945a4c20, answers=0x7f369411dfa0)
    at sres.c:2990
#7  0x00007f36d8da6368 in sres_resend_dns_query (res=0x7f3694002960, q=0x7f36945a4c20, 
    timeout=0) at sres.c:3090
#8  0x00007f36d8da725b in sres_resolver_report_error (res=0x7f3694002960, socket=129, 
    errcode=111, remote=0x7f36ab318450, remotelen=16, 
    info=0x7f36ab3183d0 "icmp type=3 code=3 reported by 127.0.0.1") at sres.c:3439
#9  0x00007f36d8da6f29 in sres_resolver_error (res=0x7f3694002960, socket=129) at sres.c:3353
#10 0x00007f36d8db078d in sres_sofia_poll (magic=0x7f36ac001180, w=0x7f3694000ff4, 
    reg=0x7f3694003790) at sresolv.c:357
#11 0x00007f36d8db69ac in su_epoll_port_wait_events (self=0x7f36940008c0, tout=0)
    at su_epoll_port.c:510
#12 0x00007f36d8dbc17f in su_port_wait_events (self=0x7f36940008c0, timeout=0) at su_port.h:318
#13 0x00007f36d8dbd481 in su_root_yield (self=0x7f3694001130) at su_root.c:904
#14 0x00007f36d8d71ffd in nua_stack_timer (nua=0x7f36ac001180, t=0x7f36940011e0, a=0x0)
    at nua_stack.c:739
#15 0x00007f36d8dc69f9 in su_timer_expire (timers=0x7f3694000908, timeout=0x7f36ab318cd8, 
    now=...) at su_timer.c:585
#16 0x00007f36d8db4ee2 in su_base_port_run (self=0x7f36940008c0) at su_base_port.c:339
#17 0x00007f36d8dbc1aa in su_port_run (self=0x7f36940008c0) at su_port.h:326
#18 0x00007f36d8dbd284 in su_root_run (self=0x7f3694001130) at su_root.c:819
#19 0x00007f36d8dbb933 in su_pthread_port_clone_main (varg=0x7f36d8abb4a0)
    at su_pthread_port.c:343
#20 0x00007f36e6ec9e65 in start_thread () from /lib64/libpthread.so.0
#21 0x00007f36e651e88d in __libc_ifunc_impl_list () from /lib64/libc.so.6
#22 0x0000000000000000 in ?? ()

Thanks!

**Comment by dragos-oancea** [comment]
same as: https://github.com/signalwire/freeswitch/issues/1659
